meals = [
    {
      "idMeal": "53262",
      "strMeal": "Adana kebab",
      "strMealAlternate": null,
      "strCategory": "Lamb",
      "strArea": "Turkish",
      "strInstructions": "step 1\r\nFinely chop the peppers in a food processor, then tip them in a sieve and press into the sieve so that the peppers release all of their juices. Tip into a bowl along with the mince, red pepper paste, pul biber, 1½ tsp flaky sea salt, and 2 tbsp of the oil. Mix together, kneading well for at least 2-3 mins. If you need to, wet your hands with cold water to prevent the mixture from sticking. The mixture should be sticky when ready. Cover and chill for at least 2 hrs, or up to 12 hrs.\r\n\r\nstep 2\r\nWhen ready to cook, heat the grill to high or an oven to 220C/200C fan/gas 6. Divide the mixture into 12 equal portions, around 85g each. If you’d like to skewer them, divide into 8 equal portions and roll into balls. Using wet hands, thread the balls onto the end of the skewers, massaging the mixture down the skewers in between the palms of your hands, until evenly distributed. Ensure that the mixture is fully wrapped tightly around the skewers without any exposed metal. Alternatively, lay them on a large baking tray lined with parchment paper if cooking in the oven, or foil if cooking under the grill. Shape into 20cm-long köfte. Wet your fingers with a little cold water and make indents all along the köfte for the traditional shape.\r\n\r\nstep 3\r\nGently brush each köfte with the remaining 1 tbsp oil and cook under the grill, on the top shelf for 10-12 mins, turning regularly, or cook in the oven for 16-18 mins, until crispy on the outside and juicy in the middle",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/04axct1763793018.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=Wj7sXu9B_ME",
      "strIngredient1": "Romano Pepper",
      "strIngredient2": "Lamb Mince",
      "strIngredient3": "Red Pepper Paste",
      "strIngredient4": "Pul Biber",
      "strIngredient5": "Sunflower Oil",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "800g",
      "strMeasure3": "3  tablespoons",
      "strMeasure4": "1 tablespoon",
      "strMeasure5": "3  tablespoons",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/adana-kebab",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-22 06:28:49"
    },
    {
      "idMeal": "53373",
      "strMeal": "Air Fryer Egg Rolls",
      "strMealAlternate": null,
      "strCategory": "Side",
      "strArea": "Chinese",
      "strInstructions": "Alternative Pan Fry Method: If you don’t have access to an air fryer, you can make these egg rolls using a traditional pan fry method. Add enough oil to a medium skillet with high walls so the oil is about 1/2 inch up the side of the skillet. Heat oil on medium high heat until it reaches 350°F. Add egg rolls and fry for 3 to 4 minutes, flip, and fry for another 3 to 4 minutes until golden brown. Remove and let them drain and cool on a few paper towels.\r\n\r\nCook the filling:\r\nIn a large skillet over medium heat, add the olive oil along with the ground pork or chicken. Break apart the meat with a spatula or wooden spoon as it cooks. Cook until the meat is cooked through, 6 to 8 minutes.\r\n\r\nAdd garlic, ginger, carrot, scallions, and cabbage. Continue to cook until cabbage wilts down and is soft, another 3 to 4 minutes, stirring regularly. Season the filling with soy sauce and rice wine vinegar, and take off the heat to cool. (This filling can be made in advance.)\r\n\r\nAssemble the egg rolls:\r\nPlace a single egg roll wrapper on a dry surface with one point of the square facing you (like a diamond). Place about 1/4 cup of the egg roll filling mixture in the middle of the wrapper.\r\n\r\nDip your fingers in water and run around the edges of the wrapper. Then fold the edges of the wrapper over the center and start rolling the egg roll away from you to form a tight cylinder. Place on a plate and repeat until you are out of filling. You should get at least a dozen egg rolls.\r\n\r\nAir fry the egg rolls:\r\nPlace the egg rolls in the basket of your air fryer. Spray or brush them lightly with oil. Add as many as you can without stacking the egg rolls, making sure they don’t touch. Air needs to circulate around them. Brush the egg rolls lightly with oil.\r\n\r\nPlace the basket in the air fryer and turn the air fryer to 350°F. Cook for 6 to 7 minutes, then flip the egg rolls, spray or brush with oil a second time on the bottom side, and cook for another 4 to 5 minutes.\r\n\r\nFinished egg rolls should be golden brown and crispy! Serve immediately.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/grhn401765687086.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=XnA-wcVb4l0",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Ground Pork",
      "strIngredient3": "Garlic",
      "strIngredient4": "Ginger",
      "strIngredient5": "Carrots",
      "strIngredient6": "Scallions",
      "strIngredient7": "Cabbage",
      "strIngredient8": "Soy Sauce",
      "strIngredient9": "Rice Vinegar",
      "strIngredient10": "Egg Roll Wrappers",
      "strIngredient11": "Oil",
      "strIngredient12": "Duck Sauce",
      "strIngredient13": "Plum Sauce",
      "strIngredient14": "Soy Sauce",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 tablespoon",
      "strMeasure2": "1 lb",
      "strMeasure3": "1 clove peeled crushed",
      "strMeasure4": "1 tablespoon",
      "strMeasure5": "1 medium",
      "strMeasure6": "3 chopped",
      "strMeasure7": "3 Cups",
      "strMeasure8": "1 tablespoon",
      "strMeasure9": "1 tablespoon",
      "strMeasure10": "12",
      "strMeasure11": "For brushing",
      "strMeasure12": "To serve",
      "strMeasure13": "To serve",
      "strMeasure14": "To serve",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.simplyrecipes.com/recipes/air_fryer_chinese_egg_rolls/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-12-14 04:36:20"
    },
    {
      "idMeal": "53158",
      "strMeal": "Air fryer patatas bravas",
      "strMealAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nSoak the potatoes in just-boiled water for 30 mins, then drain and leave to air-dry for 5 mins. Heat the air fryer to 200C. Tip the potatoes into a bowl and drizzle over 1 tbsp of the oil and add 1/2 tsp each of salt and freshly ground black pepper. Mix to coat the potatoes all over, then tip into the air fryer basket and cook for 20-30 mins until crisp and golden.\r\n\r\nstep 2\r\nMeanwhile, heat the remaining oil in a small pan over a medium-low heat and fry the onion for 8-10 mins until softened but not golden. Stir in the garlic and cook for a minute before adding the paprika and cooking for 30 seconds more. Stir in the tomato purée, cook for 1 min, then tip in the chopped tomatoes. Cook for 5-10 mins over a medium heat until thickened slightly.\r\n\r\nstep 3\r\nOnce the potatoes are cooked, tip out onto a platter and pour over the tomato sauce. Sprinkle with the basil leaves, then serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/3m8yae1763257951.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=kzLaw6PG2UY",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Onion",
      "strIngredient4": "Garlic",
      "strIngredient5": "Paprika",
      "strIngredient6": "Tomato Puree",
      "strIngredient7": "Tinned Tomatos",
      "strIngredient8": "Basil Leaves",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "900g",
      "strMeasure2": "3  tablespoons",
      "strMeasure3": "1 chopped",
      "strMeasure4": "1 clove peeled crushed",
      "strMeasure5": "1 tblsp ",
      "strMeasure6": "1 tblsp ",
      "strMeasure7": "225g",
      "strMeasure8": "To serve",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/air-fryer-patatas-bravas",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 01:49:18"
    },
    {
      "idMeal": "53169",
      "strMeal": "Ajo blanco",
      "strMealAlternate": null,
      "strCategory": "Starter",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nTip the bread into a bowl and pour over 350ml water. Leave to soak for 10 mins.\r\n\r\nstep 2\r\nBlend the ingredients together with 350ml water and 1 tsp salt.\r\n\r\nstep 3\r\nLet the soup cool in the fridge for 1 hr or so, then serve with a drizzle of oil and some black pepper.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/5jdtie1763289302.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=AS2mSRtWyW0",
      "strIngredient1": "White bread",
      "strIngredient2": "Almonds",
      "strIngredient3": "Extra Virgin Olive Oil",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Red Wine Vinegar",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "150g",
      "strMeasure2": "200g",
      "strMeasure3": "50 ml ",
      "strMeasure4": "1",
      "strMeasure5": "1 ½ tbsp",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/ajo-blanco",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 10:32:44"
    }
]
